name: Test Published Event

on:
  release:
    types: [published]

  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: always()

      - name: Set Versions
        uses: actions/github-script@v6
        id: set_version
        with:
          script: |
            console.log(JSON.stringify(context));
            console.log(JSON.stringify(github));
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')

            const no_v2 = github.event.release.tag_name.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-v2', no_v2)
            core.setOutput('no-dash', no_dash)

      - name: Build, Push Helm Chart
        env:
          IMAGE_TAG: ${{ github.event.release.tag_name }}

        run: |-
          echo ${{steps.set_version.outputs.no-v}}
          echo ${{steps.set_version.outputs.no-v2}}
          cd xyz/etc/helm
          
          sed -i "s/^version:.*$/version: ${{ github.event.release.tag_name }}/" xyz/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: \"${{ github.event.release.tag_name }}\"/" xyz/Chart.yaml
          
          cat xyz/Chart.yaml


      



