name: Test Published Event

on:
  release:
    types: [published]

  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: always()

      - name: Set Versions
        uses: actions/github-script@v6
        id: set_version
        with:
          script: |
            core.setOutput('tag', context.payload.release.tag_name.replace('v', ''));

      - name: Build, Push Helm Chart
        env:
          IMAGE_TAG: ${{ steps.set_version.outputs.tag }}

        run: |-
          echo ${{steps.set_version.outputs.tag}}
          cd xyz/etc/helm
          
          sed -i "s/^version:.*$/version: ${{ steps.set_version.outputs.tag }}/" xyz/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: \"${{ steps.set_version.outputs.tag }}\"/" xyz/Chart.yaml
          
          cat xyz/Chart.yaml


      



