name: Test Published Event

on:
  release:
    types: [published]

  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: always()

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Build, Push Helm Chart
        env:
          IMAGE_TAG: ${{ github.event.release.tag_name }}

        run: |-
          cd xyz/etc/helm
          
          sed -i "s/^version:.*$/version: ${{ github.event.release.tag_name }}/" xyz/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: \"${{ github.event.release.tag_name }}\"/" xyz/Chart.yaml
          
          cat xyz/Chart.yaml


      



